import { Router } from "express";
import healthRouter from "./health.js";
import productsRouter from "./products.js";
import evaluationsRouter from "./evaluations.js";
import alternativesRouter from "./alternatives.js";
import scanRouter from "./scan.js";
import submissionsRouter from "./submissions.js";
import preferencesRouter from "./preferences.js";
import referenceRouter from "./reference.js";
import adminRouter from "./admin.js";
import goalsRouter from "./goals.js";
import mealLogsRouter from "./mealLogs.js";
import searchRouter from "./search.js";
import guidesRouter from "./guides.js";
import collectionsRouter from "./collections.js";
import newsRouter from "./news.js";
import safetyAlertsRouter from "./safetyAlerts.js";
import decisionOutcomesRouter from "./decisionOutcomes.js";
import scientificEvidenceRouter from "./scientificEvidence.js";

const router = Router();

router.use(healthRouter);
router.use(productsRouter);
router.use(evaluationsRouter);
router.use(alternativesRouter);
router.use(scanRouter);
router.use(submissionsRouter);
router.use(preferencesRouter);
router.use(referenceRouter);
router.use(adminRouter);
router.use(goalsRouter);
router.use(mealLogsRouter);
router.use(searchRouter);
router.use(guidesRouter);
router.use(collectionsRouter);
router.use(newsRouter);
router.use(safetyAlertsRouter);
router.use(decisionOutcomesRouter);
router.use(scientificEvidenceRouter);

export default router;
