import {
  bigserial,
  bigint,
  boolean,
  date,
  index,
  integer,
  jsonb,
  numeric,
  pgTable,
  serial,
  text,
  timestamp,
  uniqueIndex,
} from "drizzle-orm/pg-core";

export const scientificEvidenceTopicsTable = pgTable("scientific_evidence_topics", {
  id: serial("id").primaryKey(),
  canonicalName: text("canonical_name").notNull().unique(),
  displayNameZh: text("display_name_zh"),
  topicType: text("topic_type").notNull().default("ingredient"),
  aliases: jsonb("aliases").notNull().default([]),
  queryTerms: jsonb("query_terms").notNull().default([]),
  isActive: boolean("is_active").notNull().default(true),
  lastSyncedAt: timestamp("last_synced_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const scientificEvidenceSyncRunsTable = pgTable("scientific_evidence_sync_runs", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  provider: text("provider").notNull(),
  topicId: integer("topic_id").references(() => scientificEvidenceTopicsTable.id),
  queryText: text("query_text"),
  rangeStart: date("range_start").notNull(),
  rangeEnd: date("range_end").notNull(),
  cursorStart: text("cursor_start"),
  cursorEnd: text("cursor_end"),
  status: text("status").notNull().default("running"),
  fetchedCount: integer("fetched_count").notNull().default(0),
  acceptedCount: integer("accepted_count").notNull().default(0),
  rejectedCount: integer("rejected_count").notNull().default(0),
  duplicateCount: integer("duplicate_count").notNull().default(0),
  integrityExcludedCount: integer("integrity_excluded_count").notNull().default(0),
  licensedFullTextCount: integer("licensed_full_text_count").notNull().default(0),
  qualitySummary: jsonb("quality_summary").notNull().default({}),
  errorMessage: text("error_message"),
  startedAt: timestamp("started_at", { withTimezone: true }).notNull().defaultNow(),
  finishedAt: timestamp("finished_at", { withTimezone: true }),
});

export const scientificEvidenceSourcesTable = pgTable("scientific_evidence_sources", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  lastSyncRunId: bigint("last_sync_run_id", { mode: "number" }).references(() => scientificEvidenceSyncRunsTable.id, { onDelete: "set null" }),
  provider: text("provider").notNull(),
  externalId: text("external_id").notNull(),
  pmid: text("pmid"),
  pmcid: text("pmcid"),
  doi: text("doi"),
  title: text("title").notNull(),
  abstractText: text("abstract_text"),
  abstractSha256: text("abstract_sha256"),
  fullTextText: text("full_text_text"),
  fullTextSha256: text("full_text_sha256"),
  journal: text("journal"),
  publicationDate: date("publication_date"),
  publicationYear: integer("publication_year"),
  publicationTypes: jsonb("publication_types").notNull().default([]),
  meshTerms: jsonb("mesh_terms").notNull().default([]),
  authors: jsonb("authors").notNull().default([]),
  sourceUrl: text("source_url").notNull(),
  isOpenAccess: boolean("is_open_access").notNull().default(false),
  licenseId: text("license_id"),
  contentReuseStatus: text("content_reuse_status").notNull().default("metadata_only"),
  studyDesign: text("study_design").notNull().default("other"),
  studyDesignRank: integer("study_design_rank").notNull().default(90),
  integrityStatus: text("integrity_status").notNull().default("unchecked"),
  integrityCheckedAt: timestamp("integrity_checked_at", { withTimezone: true }),
  qualityFlags: jsonb("quality_flags").notNull().default([]),
  rawMetadata: jsonb("raw_metadata").notNull().default({}),
  retrievedAt: timestamp("retrieved_at", { withTimezone: true }).notNull().defaultNow(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, table => [
  uniqueIndex("scientific_evidence_sources_provider_external_uidx").on(table.provider, table.externalId),
  uniqueIndex("scientific_evidence_sources_pmid_uidx").on(table.pmid),
  index("scientific_evidence_sources_doi_idx").on(table.doi),
  index("scientific_evidence_sources_date_idx").on(table.publicationDate),
  index("scientific_evidence_sources_integrity_idx").on(table.integrityStatus, table.studyDesignRank),
]);

export const scientificEvidenceTopicLinksTable = pgTable("scientific_evidence_topic_links", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  sourceId: bigint("source_id", { mode: "number" }).notNull().references(() => scientificEvidenceSourcesTable.id),
  topicId: integer("topic_id").notNull().references(() => scientificEvidenceTopicsTable.id),
  syncRunId: bigint("sync_run_id", { mode: "number" }).references(() => scientificEvidenceSyncRunsTable.id, { onDelete: "set null" }),
  matchedTerms: jsonb("matched_terms").notNull().default([]),
  relevanceMethod: text("relevance_method").notNull().default("query_match"),
  relevanceScore: numeric("relevance_score", { precision: 5, scale: 4 }),
  consumerUseStatus: text("consumer_use_status").notNull().default("pending_review"),
  reviewStatus: text("review_status").notNull().default("not_reviewed"),
  reviewedAt: timestamp("reviewed_at", { withTimezone: true }),
  reviewedBy: text("reviewed_by"),
  qualityFlags: jsonb("quality_flags").notNull().default([]),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, table => [
  uniqueIndex("scientific_evidence_topic_links_uidx").on(table.sourceId, table.topicId),
  index("scientific_evidence_topic_links_queue_idx").on(table.topicId, table.consumerUseStatus, table.reviewStatus),
  index("scientific_evidence_topic_links_sync_run_idx").on(table.syncRunId),
]);

export const scientificEvidenceClaimsTable = pgTable("scientific_evidence_claims", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  sourceId: bigint("source_id", { mode: "number" }).notNull().references(() => scientificEvidenceSourcesTable.id),
  topicId: integer("topic_id").notNull().references(() => scientificEvidenceTopicsTable.id),
  populationText: text("population_text"),
  exposureText: text("exposure_text"),
  comparatorText: text("comparator_text"),
  outcomeText: text("outcome_text"),
  direction: text("direction").notNull().default("unclear"),
  effectEstimate: jsonb("effect_estimate"),
  limitations: jsonb("limitations").notNull().default([]),
  extractionStatus: text("extraction_status").notNull().default("not_queued"),
  bodyCertainty: text("body_certainty"),
  consumerSummaryZh: text("consumer_summary_zh"),
  sourceQuoteLocator: text("source_quote_locator"),
  reviewedAt: timestamp("reviewed_at", { withTimezone: true }),
  reviewedBy: text("reviewed_by"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});
